# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c3f31ffd-6095-4a68-bcff-70dc22da38d5";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "autodefrag"
        "space_cache=v2"
        "compress=zstd:5"
        "noatime"
        "nodiratime"
        "discard=async"
      ];
    };

  boot.initrd.luks.devices."luks-c4b71723-fb41-4064-95d6-b97d1af31c22".device = "/dev/disk/by-uuid/c4b71723-fb41-4064-95d6-b97d1af31c22";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/81FD-5CCC";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  boot.kernelParams = [ "resume=/dev/sda6" ];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4396a5be-1bd5-48e6-9e31-d542b4ca6ecc"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
